spring.application.name=pos-backend
server.port=9090

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/homeware_pos
spring.datasource.username=postgres
spring.datasource.password=pass123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect